name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make
      run: make
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: 
    
    - name: Cunit
      run: git clone https://github.com/wpdk/CUnit ; cd CUnit ; make
      
    - name: Run tests ok
      run: make test_ok
      
    - name: Run all tests
      run: make test
