name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download CUnit
      run:  wget https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
      
    - name: Install Cunit
      run: bunzip2 CUnit-2.1-3.tar.bz2 ;  tar -xvf CUnit-2.1-3.tar ; cd CUnit-2.1-3 ; aclocal ; autoconf ; automake ; chmod u+x configure ; ./configure --prefix=/usr ; make ; make install
      
    - name: Make
      run: make
      
    - name: Run tests ok
      run: make test_ok
      
    - name: Run all tests
      run: make test
