name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Make
      run: make

  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Valgrind
      run: sudo apt install -y valgrind

    - name: Make
      run: make

    - name: Tests (except CUnit test's)
      run: make test_all_except_cunit_tests

